/*
|===============================================================================
|		Last Modified Date 	: 06/02/2016
|		Developer			: Shashidhar and alwyn
|===============================================================================
|	   	File Name		: usnFields.js
|			Description	:
|						Arrays
|
|===============================================================================
*/

var fields={
	    
			"Region":{	0:"Region",
						1:"Bengaluru",
						2:"Belagavi",
						3:"Kalaburagi",
						4:"Mysuru"
					},
	   
	    
			"College Code":{
				1:{
					"AY":"ACHARAYA INSTITUTE OF TECHNOLOGY",
					"AP":"A.P.S COLLEGE OF ENGINEERING",
					"AA":"ACHARYS NRV SCHOOL OF ARCHITECTURE",
					"AO":"ACHUTHA INSTITUTE OF TECHNOLOGY",
					"AH":"ACS COLLEGE OF ENGINEERING",
					"AK":"AKSHAYA INSTITUTE OF TECHNOLOGY",
					"AC":"ALPHA COLLEGE OF ENGINEERING",
					"AM":"AMC ENGINEERING COLLEGE",
					"AR":"AMRUTHA INSTITUTE OF ENGINEERING AND MGMT. SCIENCES",
					//"AS":"",
					"AT":"ATRIA INSTITUTE OF TECHNOLOGY",
					"AU":"NANDI INSTITUTE OF TECHNOLOGY MANAGEMENT SCIENCES",
					"AJ":"ADARSHA INSTITUTE OF TECHNOLOGY",
					"BG":"B.N.M.INSTITUTE OF TECHNOLOGY",
					"BT":"B.T.L.INSTITUTE OF TECHNOLOGY",
					"BC":"BANGALORE COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"BI":"BANGALORE INSTITUTE OF TECHNOLOGY",
					"BH":"BANGALORE TECHNOLOGICAL INSTITUTE",
					//"BS":"",
					"BM":"BMS COLLEGE OF ENGINEERING",
					"BE":"BMS EVENING COLLEGE OF ENGINEERING",
					"BY":"BMS INSTITUTE OF TECHNOLOGY",
					"BO":"BRINDAVAN COLLEGE OF ENGG",
					"CK":"C BYEREGOWDA INSTITUTE OF TECHNOLOGY",
					"CR":"C.M.R INSTITUTE OF TECHNOLOGY",
					"CD":"CAMBRIDGE INSTITUTE OF TECHNOLOGY",
					"CG":"CHANNA BASAVESHWARA INSTITUTE OF TECHNOLOGY",
					"CE":"CITY ENGINEERING COLLEGE",
					"CS":"SHARADA SCHOOL OF ARCHITECTURE & PLANNING",
					"DT":"DAYANANDA SAGAR ACADEMY OF TECHNOLOGY AND MGMT",
					"DS":"DAYANANDA SAGAR COLLEGE OF ENGINEERING",
					"DB":"DON BOSCO INSTITUTE OF TECHNOLOGY",
					"CC":"Dr. Sri Sri Sri SHIVKUMAR MAHASWAMY COLLEGE OF ENGG",
					"DA":"DR. AMBEDKAR INSTITUTE OF TECHNOLOGY",
					"GV":"DR. T THIMAIAH INSTITUTE OF TECHNOLOGY",
					"EC":"EAST POINT COLLEGE OF ENGG. FOR WOMEN",
					"EP":"EAST POINT COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"EW":"EAST WEST INSTITUTE OF TECHNOLOGY",
					//"GS":"",
					"GC":"GHOUSIA COLLEGE OF ENGINEERING",
					"GA":"GLOBAL ACADEMY OF TECHNOLOGY",
					"GD":"GOPALAN COLLEGE OF ENGINEERING  MANAGEMENT",
					"SK":"GOVERNMENT S.K.S.J.T. INSTITUTE OF TECHNOLOGY",
					"SE":"GOVERNMENT SKSJT EVENING COLLEGE",
					"GT":"GOVERNMENT TOOL ROOM AND TRAINING CENTRE",
					"GG":"GOVT. ENGINEERING COLLEGE RAMNAGAR",
					"HK":"HKBK COLLEGE OF ENGINEERING",
					"HM":"HMS INSTITUTE OF TECHNOLOGY",
					"IC":"IMPACT COLLEGE OF ENGINEERING",
					"II":"ISLAMIAH INSTITUTE OF TECHNOLOGY",
					"IS":"SRI VIDYA VINYAKA INSTITUTE OF TECHNOLOGY",
					"JV":"JNANA VIKAS INSTITUTE OF TENCNOLOGY",
					"JS":"JSS ACADEMY OF TECHNICIAL EDUCATION",
					"JT":"JYOTHY INSTITUTE OF TECHNOLOGY",
					"KS":"K.S.INSTITUTE OF TECHNOLOGY",
					"KI":"KALPATARU INSTITUTE OF TECHNOLOGY",
					"KN":"KNS INSTITUTE OF TECHNOLOGY",
					"ME":"M.S.ENGINEERING COLLEGE",
					"MS":"M.S.RAMAIAH INSTITUTE OF TECHNIOLOGY",
					"MJ":"MVJ COLLEGE OF ENGINEERING",
					//"NJ":"",
					"NC":"NAGARJUNA COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"NH":"NEW HORIZON COLLEGE OF ENGINEERING",
					"NT":"NITTE MEENAKSHI INSTITUTE OF TECHNOLOGY",
					"OX":"OXFORD COLLEGE OF ENGINEERING",
					"PI":"PES INSTITUTE OF TECHNOLOGY",
					"PN":"P N S  INSTITUTE OF TECHNOLOGY",
					"PE":"PES SCHOOL OF ENGINEERING",
					"RI":"R R INSTITUTE OF TECHNOLOGY",
					"RL":"R.L.JALAPPA INSTITUTE OF TECHNOLOGY",
					"RV":"R.V.COLLEGE OF ENGINEERING",
					"RR":"RAJARAJESWARI COLLEGE OF ENGINEERING",
					"RG":"RAJIV GANDHI INSTITUTE OF TECHNOLOGY",
					"RE":"REVA INSTITUTE OF  TECHNOLOGY & MANAGEMENT",
					"RN":"RNS INSTITUTE OF TECHNOLOGY",
					"SJ":"S.J.C INSTITUTE OF TECHNOLOGY",
					"VA":"SAI VIDYA INSTITUTE OF TECHNOLOGY",
					"ST":"SAMBHRAM INSTITUTE OF TECHNOLOGY",
					"SZ":"SAMPOORNA INSTITUTE OF TECHNOLOGY  RESEARCH",
					"SG":"SAPTHAGIRI COLLEGE OF ENGINEERING",
					"SC":"SCT INSTITUTE OF TECHNOLOGY",
					"SP":"SEA COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"HS":"SHASHIB COLLEGE OF ENGINEERING",
					"SB":"SRI SAIRAM COLLEGE OF ENGINEERING",
					"SV":"SHRIDEVI INSTITUTE OF ENGINEERING AND TECHNOLOGY",
					"SI":"	SIDDAGANGA INSTITUTE OF TECHNOLOGY",
					"MV":"SIR M. VISVESVARAYA INSTITUTE OF TECHNOLOGY",
					"JB":"SJB INSTITUTE OF TECHNOLOGY",
					//"SW":"",
					//"BN":"",
					"KT":"SRI KRISHNA INSTITUTE OF TECHNOLOGY",
					"KG":"K.S SCHOOL OF ENGG & MGMT",
					//"KH":"",
					"RC":"SRI REVANASIDDESHWARA INSTITUTE OF TECHNOLOGY",
					"VE":"SRI VENKATESHWARA COLLEGE OF ENGINEERING",
					"TJ":"T. JOHN INSTITUTE OF TECHNOLOGY",
					"VI":"VEMANA INSTITUTE OF TECHNOLOGY",
					"VJ":"VIJAYA VITTALA INSTITUTE OF TECHNOLOGY",
					"VK":"VIVEKANANDA INSTITUTE OF TECHNOLOGY",
					"VG":"SRI VIDYA VINYAKA INSTITUTE OF TECHNOLOGY",
					"YD":"YELLAMMA DASAPPA INSTITUTE OF TECHNOLOGY"
				},
				2:{
					"AV":"AGM RURAL COLLEGE OF ENGINEERING & TECHNOLOGY",
					"AG":"ANGADI INSTITUTE OF TECHNOLOGY AND MGMT",
					"AB":"ANJUMAN  INSTITUTE OF TECHNOLOGY & MANAGEMENT",
					"BV":"B.V.BHOOMARADDI COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"BA":"BASAVESHWARA ENGINERING COLLEGE",
					"BL":"BLDEAS COLLEGE OF ENGINEERING",
					"GP":"GOVERNMENT ENGINEERING COLLEGE KARWAR",
					"GO":"GOVT. ENGINEERING COLLEGE HAVERI",
					"GB":"GOVT. ENGINEERING COLLEGE HUVINHADAGALI",
					"HN":"HIRASUGAR INSTITUTE OF TECHNOLOGY",
					"JM":"JSS ACADEMY OF TECHNICAL EDUCATION",
					"JI":"JAIN COLLEGE OF ENGINEERING",
					"KD":"KLE COLLEGE OF ENG. AND TECHNOLOGY CHIKODI",
					"KE":"KLE INSTITUTE OF TECH HUBLI",
					"KL":"KLE Dr M. S. SHESHGIRI COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"GI":"KLS GOGTE INSTITUTE OF TECHNOLOGY",
					"MB":"MALIK SANDAL INSTITUTE OF ART AND ARCHITECTURE",
					"MM":"MARATHA MANDALS ENGINEERING COLLEGE",
					"RH":"RURAL ENGINEERING COLLEGE, HULKOTI",
					"BU":"S G BALEKUNDRI INST. OF TECH",
					"SR":"S.T.J. INSTITUTE OF TECHNOLOGY",
					"SD":"SDM COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"SA":"SECAB INSTITUTE OF ENGINEERING AND TECHNOLOGY",
					"HA":"SHAIKH COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"KA":"SMT. KAMALA AND SRI VENKAPPA M. AGADI COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"TG":"SRI TONTADARAYA COLLEGE OF ENGINEERING",
					"VS":"V S M’S INSTITUTE OF TECHNOLOGY",
					"VD":"VISHWANATHA RAO DESHPANDE RURAL INSTITUTE OF TECHNOLOGY"
				},
				3:{
					"AE":"APPA INSTITUTE OF ENGINEERING AND TECHNOLOGY",
					"BK":"BASAVAKALYAN ENGINEERING COLLEGE",
					"BR":"BELLARY ENGINEERING COLLEGE",
					"GF":"GODUTAI ENGINEERING COLLEGE FOR WOMEN",
					"GU":"GOVT. ENGINEERING COLLEGE RAICHUR",
					"GN":"GURU NANAK DEV ENGINEERING COLLEGE",
					"KC":"K.C.T. ENGINEERING COLLEGE",
					"KB":"KHAJA BANDA NAWAZ COLLEGE OF ENGINEERING",
					"LA":"LINGARAJ APPA ENGINEERING COLLEGE",
					"NA":"NAVODAYA INSTITUTE OF TECHNOLOGY",
					"PD":"POOJYA DODAPPAPPA COLLEGE OF ENGINEERING",
					"PG":"PROUDADEVARAYA INSTITUTE OF TECHNOLOGY",
					"VC":"RAO BAHADDUR Y MAHABALESHWARAPPA ENGG COLLEGE",
					"RB":"BHEEMANNA KHANDRE INSTITUTE OF TECHNOLOGY, BHALKI",
					"SL":"SLN COLLEGE OF ENGINEERING",
					"TS":"SHETTY INSTITUTE OF TECHNOLOGY",
					"VN":"VEERAPPA NISTY ENGINEERING COLLEGE"
				},
				4:{
					"AD":"ACADEMY FOR TECHNICAL AND MANAGEMENT EXCELLENCE",
					"AI":"ADICHUNCHANAGIRI INSTITUTE OF TECHNOLOGY",
					"AL":"ALVAS INST. OF ENGG. AND TECHNOLOGY",
					"LV":"ALVAS INST. OF ENGG. AND TECHNOLOGY",
					"BW":"B.G.S.INSTITUTE OF TECHONOLOGY",
					"BB":"BAHUBALI COLLEGE OF ENGINEERING",
					"BD":"BAPUJI INSTITUTE OF ENGINEERING AND TECHNOLOGY",
					"BP":"BEARYS INSTITUTE OF TECHNOLOGY",
					"CB":"CANARA ENGINEERING COLLEGE",
					"CI":"COORG INSTITUTE OF TECHNOLOGY",
					"DM":"DR. M V SHETTY INSTITUTE OF TECHNOLOGY",
					"EK":"EKALAVYA INSTITUTE OF TECHNOLOGY",
					"MG":"G MADEGOWDA INSTITUTE OF TECHNOLOGY",
					"GM":"GM.INSTITUTE OF TECHONOLOGY",
					"GE":"GOVT. ENGINEERING COLLEGE CHAMARAJANAGARA",
					"GH":"GOVT. ENGINEERING COLLEGE HASSAN",
					"GL":"GOVT. ENGINEERING COLLEGE KUSHAL NAGAR",
					"GK":"GOVT. ENGINEERING COLLEGE MANDYA",
					"GR":"GOVT. TOOL ROOM AND TRAINING CENTRE",
					"GW":"GSSS INSTITUTE OF ENGINEERING AND TECHNOLOGY FOR WOMEN",
					"JN":"JAWAHARLAL NEHRU NATIONAL COLLEGE OF ENGINERING",
					"JC":"SRI JAYACHAMARAJENDRA COLLEGE OF ENGINEERING",
					"JE":"SRI JAYACHAMRAJENDRA COLLEGE OFF ENGG. EVENING ",
					"KV":"K.V.G. COLLEGE OF ENGINEERING",
					"KM":"KARAVALI INSTITUTE OF TECHNOLOGY",
					"MH":"MAHARAJA INSTITUTE OF TECH",
					"MC":"MALNAD COLLEGE OF ENGINEERING",
					"MT":"MANGALORE INSTITUTE OF TECHNOLOGY AND ENGINEERING",
					"MK":"MOODLAKATTE INSTITUTE OF TECHONOLOGY",
					"NE":"NATIONAL INSTITUTE OF ENGG. EVENING",
					"NI":"NATIONAL INSTITUTE OF ENGINEERING ",
					"NN":"NIE INST. OF TECHNOLOGY",
					"NM":"NMAM INSTITUTE OF TECHONOLOGY",
					"PA":"P.A.COLLEGE OF ENGINEERING",
					"PM":"PES INSITUTE OF TECHNOLOGY AND MGMT",
					"PR":"PRASANNA ENGINEERING AND TECHNOLOGY",
					//"QB":"",
					"RA":"RAJEEV INST. OF TECHNOLOGY ",
					"SF":"SAHYADRI COLLEGE OF ENGINEERING & MANAGEMENT MANGALORE",
					"SX":"SAHYADRI COLLEGE OF ENGINEERING & MANAGEMENT MANGALORE",
					"SH":"SHREE DEVI INSTITUTE OF TECHNOLOGY",
					"PH":"SHREE DEVI INSTITUTE OF TECHNOLOGY",
					"MW":"SHRI MADHWA VADIRAJA INSTITUTE OF TECHNOLOGY & MANAGEMENT",
					"SM":"SJM INSTITUTE OF TECHNOLOGY",
					"SU":"SRI DHARMASTHAL MANJUNATHESHWAR INSTITUTE OF TECHNOLOGY",
					"SN":"SRINIVAS INSTITUTE OF TECHNOLOGY",
					"ES":"SRINIVAS SCHOOL OF ENGINEERING",
					"SO":"ST.JOSPEH ENGINEERING COLLEGE",
					"UB":"UBDT ENGINEERING  COLLEGE DAVANAGERE(Constituent College of VTU)",
					"VV":"VIDYA VARDHAKA COLLEGE OF ENGINERING",
					"VM":"VIDYA VIKAS INSTITUTE OF ENGINEERING AND TECHNOLOGY",
					"VP":"VIVEKANANDA COLLEGE OF ENGINEERING AND TECHNOLOGY",
					"YG":"YAGACHI INSTITUTE OF TECHNOLOGY"
				}
			},
	    
			"YY":[14],
	    
	    	"Branch":{
						"BE":{ 
								"AE":"Aeronautical Engineering",
								"AT":"Architecture",
								"AU":"Automobile Engineering",
								"BM":"Biomedical Engineering",
								"BT":"Bio-technology",
								"CC":"Ceramics and Cement Technology",
								"CH":"Chemical Engineering",
								"CS":"Computer Science and Engineering",
								"CT":"Construction Technology and Management",
								"CV":"Civil Engineering",
								"EC":"Electronics and Comm Engineering",
								"EE":"Electrical and Electronics Engineering",
				     			"EV":"Environmental Engineering",
				     			"IM":"Industrial Engineering and Management",
				     			"IP":"Industrial and Production Engineering",
				     			"IS":"Information Science and Engineering",
				     			"IT":"Instrumentation Technology",
				     			"ME":"Mechanical Engineering",
				     			"MI":"Mining Engineering",
				     			"ML":"Medical Electronics",
				     			"MS":"Manufacturing Science and Engineering",
				     			"PM":"Polymer Science and Technology",
				     			"ST":"Silk Technology",
				     			"TE":"Telecommunication Engineering",
				     			"TX":"Textile Technology"
							},
			
						"MTECH":{
					    			"ECD":"Computer Applications in Industrial Drives",
					    			"CHT":"Highway Technology",
					    			"CSE":"Structural Engineering",
					    			"CTM":"Transportation Engineering and Management",
					    			"CCS":"Computer Aided Design of Structures",
					    			"CCT":"Construction Technology",
					    			"CEE":"Environmental Engineering",
					    			"EMS":"Microelectronics and Control Systems",
					    			"EPE":"Power Electronics",
					    			"EPS":"Power Systems Engineering",
					    			"HCE":"Chemical Engineering",
					    			"JTT":"Textile Technology",
					    			"LBI":"Biomedical Signal Processing and Instrumentation",
					    			"LCS":"Communication Systems",
					    			"LDC":"Digital Communications Engineering",
					    			"LDE":"Digital Electronics",
					    			"LDN":"Digital Communications and Networking",
					    			"LDS":"Digital Electronics and Communcation Systems",
					    			"LEL":"Electronics",
					    			"LIE":"Industrial Electronics",
					    			"LNI":"Networking and Internet Engineering",
					    			"LSP":"Signal Processing",
					   	 			"LVS":"VLSI Design and Embedded Systems",
					   	 			"MAE":"Master of Aeronautical Engineering",
					   	 			"MAR":"Industrial Automation and Robotics",
					   	 			"MAU":"Master of Automotive Engineering",
					   	 			"MBA":"Master of Business Administration",
					   	 			"MCA":"Master of Computer Applications",
					   	 			"MCM":"Computer Integrated Manufacturing",
					   	 			"MCS":"Computational Analysis in Mechanical Sciences",
					   	 			"MDE":"Design Engineering",
					   	 			"MEA":"Engineering Analysis and Design",
					   	 			"MEM":"Master of Engineering Management",
					    			"MMD":"Machine Design",
					    			"MPD":"Product Design and Manufacturing",
					    			"MPT":"Production Engineering and System Technology",
					    			"MSE":"Production Engineering",
					    			"MTE":"Tool Engineering",
					    			"MTH":"Thermal Engineering",
					    			"MTP":"Thermal Power Engineering",
					    			"SCE":"Computer Engineering",
					    			"SCN":"Computer Network Engineering",
					    			"SCS":"Computer Science and Engineering",
					    			"SIT":"Information Technology",
					    			"SSE":"Software Engineering"
								},
	    			}
		};
